[[plugins]]
name = "buf.build/grpc-ecosystem/openapiv2"
plugin_version = "v2.26.1"
output_languages = [
    "application_plugins",
]

[[plugins]]
name = "buf.build/grpc/csharp"
plugin_version = "v1.70.1"
output_languages = [
    "csharp",
]
deps = [
    { p_name = "buf.build/protocolbuffers/csharp", version = "v29.3" },
]

[plugins.registry]
opts = [
    "base_namespace=",
]

[plugins.registry.nuget]
target_frameworks = [
    "netstandard2.0",
]
deps = [
    { name = "Grpc.Net.Common", version = "2.67.0" },
]

[[plugins]]
name = "buf.build/protocolbuffers/csharp"
plugin_version = "v29.3"
output_languages = [
    "csharp",
]

[plugins.registry]
opts = [
    "base_namespace=",
]

[plugins.registry.nuget]
target_frameworks = [
    "netstandard2.0",
]
deps = [
    { name = "Google.Protobuf", version = "3.29.3" },
]

[[plugins]]
name = "buf.build/grpc/go"
plugin_version = "v1.3.0"
output_languages = [
    "go",
]
deps = [
    { p_name = "buf.build/protocolbuffers/go", version = "v1.34.0" },
]

[plugins.registry]
opts = [
    "paths=source_relative",
    "require_unimplemented_servers=false",
    "separate_package=true",
]

[plugins.registry.go]
deps = [
    { name = "google.golang.org/grpc", version = "v1.61.2" },
]

[[plugins]]
name = "buf.build/protocolbuffers/go"
plugin_version = "v1.33.0"
output_languages = [
    "go",
]

[plugins.registry]
opts = [
    "paths=source_relative",
]

[plugins.registry.go]
deps = [
    { name = "google.golang.org/protobuf", version = "v1.33.0" },
]

[[plugins]]
name = "buf.build/grpc/java"
plugin_version = "v1.70.0"
output_languages = [
    "java",
]
deps = [
    { p_name = "buf.build/protocolbuffers/java", version = "v29.3" },
]

[plugins.registry.maven]
deps = [
    "io.grpc:grpc-core:1.70.0",
    "io.grpc:grpc-protobuf:1.70.0",
    "io.grpc:grpc-stub:1.70.0",
    "com.google.protobuf:protobuf-java:4.29.3",
]

[[plugins]]
name = "buf.build/protocolbuffers/java"
plugin_version = "v29.3"
output_languages = [
    "java",
]

[plugins.registry.maven]
deps = [
    "com.google.protobuf:protobuf-java:4.29.3",
]

[[plugins]]
name = "buf.build/grpc/web"
plugin_version = "v1.5.0"
output_languages = [
    "javascript",
    "typescript",
]
deps = [
    { p_name = "buf.build/protocolbuffers/js", version = "v3.21.2" },
]

[plugins.registry]
opts = [
    "import_style=commonjs+dts",
    "mode=grpcweb",
]

[plugins.registry.npm]
import_style = "commonjs"
deps = [
    { name = "grpc-web", version = "^1.5.0" },
    { name = "google-protobuf", version = "^3.21.2" },
]

[[plugins]]
name = "buf.build/protocolbuffers/js"
plugin_version = "v3.21.2"
output_languages = [
    "javascript",
]

[plugins.registry]
opts = [
    "import_style=commonjs",
    "binary",
]

[plugins.registry.npm]
import_style = "commonjs"
deps = [
    { name = "google-protobuf", version = "^3.21.2" },
]

[[plugins]]
name = "buf.build/grpc/python"
plugin_version = "v1.70.1"
output_languages = [
    "python",
]
deps = [
    { p_name = "buf.build/protocolbuffers/python", version = "v29.3" },
]

[plugins.registry.python]
package_type = "runtime"
requires_python = ">=3.8"
deps = [
    "grpcio",
]

[[plugins]]
name = "buf.build/protocolbuffers/pyi"
plugin_version = "v29.3"
output_languages = [
    "python",
]

[plugins.registry.python]
package_type = "stub-only"
requires_python = ">=3.8"
deps = [
    "protobuf~=5.29.3",
    "types-protobuf~=5.29",
]

[[plugins]]
name = "buf.build/protocolbuffers/python"
plugin_version = "v29.3"
output_languages = [
    "python",
]
deps = [
    { p_name = "buf.build/protocolbuffers/pyi", version = "v29.3" },
]

[plugins.registry.python]
package_type = "runtime"
requires_python = ">=3.8"
deps = [
    "protobuf~=5.29.3",
]
