steps:
  - id: deploy-python
    name: "ghcr.io/astral-sh/uv:trixie-slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$TAG_NAME" ] ; then
          # Install keyring with Google Artifact Registry auth
          uv tool install keyring --with keyrings.google-artifactregistry-auth
          uv version ${TAG_NAME#v} --no-sync   
          uv build --upgrade 
          uv publish --index vml-api
        else
          uv build --upgrade 
        fi
    env:
      - "TAG_NAME=$TAG_NAME"

  - id: deploy-csharp
    name: "bitnami/dotnet-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cp vmlapis.csproj gen/csharp
        cd gen/csharp
        if [ "$TAG_NAME"  ] ; then
          export TAG_NAME=${TAG_NAME:1} 
          dotnet pack -o . -c Release
          dotnet nuget push vmlapis.$$TAG_NAME.nupkg --source https://api.nuget.org/v3/index.json --api-key $$NUGET_API_KEY
        else 
          export TAG_NAME=0.0.0
          dotnet pack -o . -c Release
        fi
    env:
      - "TAG_NAME=$TAG_NAME"
    waitFor: ["-"]
    secretEnv: ["NUGET_API_KEY"]

  - id: deploy-java
    name: "maven:3.6.3-jdk-8"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cp -R gen/java java-package/src/main/java
        cd java-package
        if [ "$TAG_NAME" ] ; then
          export TAG_NAME=${TAG_NAME:1}
          mvn deploy
        else
          export TAG_NAME=0.0.0
          mvn package
        fi
    env:
      - "TAG_NAME=$TAG_NAME"
    waitFor: ["-"]

  - id: test-go
    name: "golang"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if ! [ "$TAG_NAME" ] ; then
          mkdir gotest
          cp -R examples/go/AutosuggestCreateDatasetExample gotest/AutosuggestCreateDatasetExample
          cp -R examples/go/SmartscanAnnotateDocumentExample gotest/SmartscanAnnotateDocumentExample
          cp -R examples/go/SmartscanRasterizePdfExample gotest/SmartscanRasterizePdfExample
          sed -i 's/commit/$COMMIT_SHA/' go.mod.example
          cp go.mod.example gotest/AutosuggestCreateDatasetExample/go.mod
          cp go.mod.example gotest/SmartscanAnnotateDocumentExample/go.mod
          cp go.mod.example gotest/SmartscanRasterizePdfExample/go.mod
          cd gotest/AutosuggestCreateDatasetExample
          go mod tidy
          go build
          cd ../SmartscanAnnotateDocumentExample
          go mod tidy
          go build
          cd ../SmartscanRasterizePdfExample
          go mod tidy
          go build
        fi
    waitFor: ["-"]

availableSecrets:
  secretManager:
    - versionName: projects/161107618804/secrets/nuget-api-key/versions/latest
      env: "NUGET_API_KEY"
